#!/bin/dash
#=======================================================================
# File:      sch-grep-in-home
# Created:   13/10/2014
# Purpose:   get pattern from user input to kdialog, grep for pattern in
#            $HOME, list all files containing pattern, open results in kate.
# Author:    Bill Cane
# Email:     schoonerdemo@gmail.com
# Copyright: © Bill Cane
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#=======================================================================

OutputFile="$HOME/.schooner/sch-find-in-home.out"
rm -f "$OutputFile" # remove debris from previous run
Pattern="$(kdialog --inputbox 'Enter the pattern you want to grep $HOME for (results will be opened in kwrite)')"
[ "$Pattern" != '' ] || exit 1
grep -rl "$Pattern" "$HOME" |sed '/Trash/d' |sed '/sch-find-in-home.out/d' > "$OutputFile"
kwrite "$OutputFile"
