#!/bin/bash
# tasks to be run by cron at startup
declare -r EnableSource="Enabled"
source /bin/sch-source-common
declare -i	UpdateOnly=$No


#DisableSamba=$(read-sch-settings 'disable-samba-at-startup')
[[ $(read-sch-settings 'disable-samba-at-startup') == 'yes' ]] && sudo service smbd stop