#!/bin/dash
#=======================================================================
# File:      sch-backup-scripts
# Created:   14/10/2014
# Purpose:   backup sch-dev/scripts and keep ten copies back
# Author:    Bill Cane
# Email:     schoonerdemo@gmail.com
# Copyright: © Bill Cane
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#=======================================================================
. /usr/bin/sch-includes

cyclic_backup '/home/attic/sch-dev/scripts' 'scripts'

