#!/bin/dash
#=======================================================================
# File:      sch-nav-kate-to-magic-num
# Created:   17/10/2014
# Purpose:   Take a filespec and a magic number contained in that file and
#            then open kate with cursor placed at line of magic number.
# Author:    Bill Cane
# Email:     schoonerdemo@gmail.com
# Copyright: © Bill Cane
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#=======================================================================
MagicNum="$(kdialog --inputbox 'Enter the magic number you want to navigate to (results will be opened in kate)')"
[ "$MagicNum" != '' ] || exit 1

Result= "$(sch-magic-num-find $MagicNum '/home/attic/sch-dev/scripts')"
LineNum="$(echo $Result |cut -f1)"
FileSpec="$(echo $Result |cut -f1 --complement)"
kate -l "$LineNum" "$FileSpec"



