#!/bin/dash 
#=======================================================================
# File:      sch-deb-deps-diag
# Created:   09/10/2014
# Purpose:   Create and display diagram to show the dependencies of a 
#            a specified debian package.
# Notes:     Requires 'debtree' and 'dot' packages to work
# Author:    Bill Cane
# Email:     schoonerdemo@gmail.com     
# Copyright: © Bill Cane
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#=======================================================================


usage()
# Purpose: describe usage of this script
# Args:    none
# Returns: 0 success
{
cat << EOF
NAME
       sch-deb-deps-diag - Create a diagram to show the 
       dependencies of a specified debian package.

SYNOPSIS
       sch-deb-deps-diag [FILESPEC]

EXIT STATUS
       0      if OK
       1      if failed       
       
EOF
}

#[ "$#" = 1 ] || usage; exit 1
ImageFileSpec="Dependencies for $1.png"
DebFile=$1
DotFile='sch-deb-deps-diag.dot'
debtree --with-suggests "$DebFile"  >"$DotFile"
dot -T png -o "$ImageFileSpec" "$DotFile"