#!/bin/dash

# for simplicity we don't allow for re-starting sessions
rm -R $HOME/.john
PswdFile=$(mktemp .sch-johnXXXXXX) 
sudo unshadow /etc/passwd /etc/shadow > $PswdFile
sudo chmod a+rw $PswdFile
john  $PswdFile
john --show $PswdFile
rm $PswdFile
rm -R $HOME/.john

