#!/bin/bash

# URL where font files' directory structure is located
BASEURL="http://googlefontdirectory.googlecode.com/hg/"

# Where fonts are to be downloaded to; default is current dir
DESTINATIONDIR="."

# Temporary files are placed here
TEMPDIR=$(mktemp -d)

WESTERNGLYPHREGEXP='\b0x(0041|0061|00c4|00e4|00c5|00e5)\b'
# Setting KEEPONLYWESTERN to 1 makes this script remove
# downloaded fonts that do not contain Western variations
# of the letter A (e.g. A with two dots, A with ring).
KEEPONLYWESTERN=0

die()
{
    echo "$@" >&2
    exit 1
}

for necessaryprograms in perl curl ; do
    test -n "$(which ${necessaryprograms})" || die "Requires \"${necessaryprograms}\" to run"
done

for licensesubdir in apache ofl ufl ; do
    # Fetch directory listing of license's subdir at Google's server,
    # extract names of subdirectories (ignore regular files in base directory),
    # store directory names in comma-separated list ($csfontnames)
    echo "Fetching list of files licensed as \"${licensesubdir}\" from Google's server"
    csfontnames=$(curl --silent --output - "${BASEURL}${licensesubdir}/" | \
    perl -n -e 'if (m!<li><a href="([a-z0-9A-Z-]+)/">\1/</a></li>!i) { if (defined($x)) { print ",";} else {$x=1;} ; print $1; }')
    echo "Identified the following fonts in license subdirectory \"${licensesubdir}\": ${csfontnames//,/, }"

    # Process each font directory individually
    for fontname in ${csfontnames//,/ } ; do
        echo "Processing font \"${fontname}\""

        # Fetch directory listing of current font's directory,
        # extract file names of TrueType fonts in this directory (ignore all
        # other files), and store font file names in a comma-separated list
        # ($csttffilenames)
        echo "Fetching list of font files"
        csttffilenames=$(curl --silent --output - "${BASEURL}${licensesubdir}/${fontname}/" | \
        perl -n -e 'if (m!<li><a href="([^"]+[.]ttf)">\1</a></li>!i) { if (defined($x)) { print ",";} else {$x=1;} ; print $1; };' || \
        die "Could not fetch list of font files for font \"${fontname}\"" )

        # Check if listing the directory above found TrueType files
        test -z "${csttffilenames}" && echo "No .ttf files found for font \"${fontname}\"" && continue

        # "Fetch all font files for current font in one curl call
        # to exploit HTTP pipelining
        echo "Fetching font files: ${csttffilenames//,/, }"
        curl --silent --output "${DESTINATIONDIR}/#1" "${BASEURL}${licensesubdir}/${fontname}/{${csttffilenames}}" || \
        die "Could not download font files for font ${fontname}: \"${BASEURL}${licensesubdir}/${fontname}/{${csttffilenames}}\""

        for ttffilename in ${csttffilenames//,/ } ; do
            # Test if font file actually exists
            test -s ${DESTINATIONDIR}/${ttffilename} || \
            die "Font file \"${ttffilename}\" expected but not found"

            # Test for Western font support if set by user (see KEEPONLYWESTERN)
            #test ${KEEPONLYWESTERN} -eq 1 && ttfdump ${DESTINATIONDIR}/${ttffilename} | grep -q -E "${WESTERNGLYPHREGEXP}" || ( rm -f ${DESTINATIONDIR}/${ttffilename} ; echo "Removed \"${ttffilename}\", does not contain Western letters" )
        done
    done || die "Could not process font files' directory listing for license subdirectory ${licensesubdir}"
done
 
