#!/bin/dash
# File:      sch-servicemenu-actions-image-resize
# Created:   28/06/2015
# Author:    
# Email:     schoonerdemo@gmail.com
# Copyright: ©
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
. /usr/bin/sch-includes

icon="transform-scale"
input_file=$(basename "$2")
extension=$1
output_file=$input_file.$extension
dialog_passive_popup "Actions For Images" "Converting $input_file to $extension format" "$icon" 20
gm convert $input_file $output_file
dialog_passive_popup "Actions For Images" "Conversion completed - created $output_file" "$icon" 5




