#!/bin/dash 
#=======================================================================
# File:      sch-tbak-rollback
# Created:   06/10/2014
# Purpose:   Restore files from temp backup directory: part of a set of scripts to 
#            create and manage a temporary backup directory which can be
#            used to make editing of several files reasonably atomic.
# See also:  sch-tbak-mkdir, sch-tbak-rollback 
# Author:    Bill Cane
# Email:     schoonerdemo@gmail.com
# Copyright: © Bill Cane
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#=======================================================================
usage()
# Purpose: describe usage of this script
# Args:    none
# Returns: 0 success
{
cat << EOF
NAME
       sch-tbak-rollback -  Remove temp backup directory: part of a set of 
       scripts to create and manage a temporary backup directory which can
       be used to make editing of several files reasonably atomic.    

SYNOPSIS
       sch-tbak-rollback [FILE]...
       
EXIT STATUS
       0      if OK
       1      if failed       
             
USAGE
       sch-tbak-mkdir "$(TmpDir)"     # rollback the temp dir
  
EOF 
}

	# iterate through files
rm -rf "$1"

if [ "$?" = 0 ]; then
	exit 0
else
	echo "unable to rollback temp directory $TmpDir"; exit 1
fi